version: '3.4'
services:
  mongo-service:
    restart: "no"
    image: edmarr/mongo-db:latest
    ports:
      - "27017:27017"
    networks: 
      - custom-newtwork-tech
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
networks:
    custom-newtwork-tech:
        driver: bridge